[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control|Shift"

[general]
import = ["/home/jorge/.config/alacritty/dawnfox.toml"]

[window]
decorations = "None"

[mouse]
hide_when_typing = true

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
italic = { family = "FiraCode Nerd Font Mono", style = "Retina" }
bold = { family = "FiraCode Nerd Font Mono", style = "SemiBold" }
size = 13

[keyboard]
