require "config.options"
require "config.keymaps"
require "config.plugins"
require "config.impatient"
require "config.colorscheme"
require "config.lsp"
require "config.treesitter"
require "config.gitsigns"
require "config.harpoon"
require "config.lualine"
require "config.alpha"
require "config.todo"
require "config.nvim-treesitter-context"
require "config.oil"
require "config.copy-file-path"
-- require "config.autopairs"
-- require "config.bufferline"
-- require "config.comment"
