require "config.options"
require "config.keymaps"
require "config.plugins"
require "config.impatient"
require "config.colorscheme"
-- require "config.cmp"
require "config.lsp"
require "config.treesitter"
-- require "config.autopairs"
-- require "config.comment"
require "config.gitsigns"
require "config.bufferline"
require "config.lualine"
require "config.alpha"
require "config.winbar"
-- require "config.todo"
require "config.nvim-treesitter-context"
